Feature/favorites screen
vasileGrad/HungryWolfs pull request #6
Opened 2021-08-25 12:05 UTC by vasileGrad

2021-08-25 12:19 UTC, MGabi requested changes

2021-08-25 12:19 UTC, MGabi commented on app/src/main/java/com/example/hungrywolfs/model/DetailsViewModel.kt
> +                    isFavorite.value = true
You can reduce all of this to `isFavorite.value = _favoriteMeals.value?.contains(_mealDetails.value)`
Technically you assign true when other value is true, so the check is not necessary

2021-08-25 12:19 UTC, MGabi commented on app/src/main/java/com/example/hungrywolfs/model/FavoritesViewModel.kt
> +        _favoriteMeals.value = Hawk.get<MutableList<MealDetailsInfo>>("favorites")
You can call getFavorites() to remove duplicate code here

2021-08-25 12:29 UTC, cristiwd requested changes

2021-08-25 12:29 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/model/DetailsViewModel.kt
> +    private var _favoriteMeals = MutableLiveData<MutableList<MealDetailsInfo>>()
No need to use a livedata here, it could be just a list.

2021-08-26 05:16 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/Constants.kt
> +class Constants {
Why not object?

2021-08-26 06:24 UTC, vasileGrad commented on app/src/main/java/com/example/hungrywolfs/Constants.kt
> +class Constants {
I removed the class Constants.

2021-08-26 06:32 UTC, vasileGrad commented on app/src/main/java/com/example/hungrywolfs/Constants.kt
> +class Constants {
Using the first approach with the companion object inside the class will generate getter and setter instance methods for the fields to be accessible. Calling instance methods is technically more expensive than calling static methods. For this reason, the recommended practice is to define the constants in the **object**.

2021-08-26 06:45 UTC, cristiwd approved these changes

2021-08-26 07:57 UTC, mgabbi approved these changes

2021-08-26 07:59 UTC, merged